#!/usr/bin/zsh
###############
### Aliases ###
###############
# Update all standard branches
alias hgupall="\
    cd /Users/alexander/src/tuenti/current && hg pull -u && \
    cd /Users/alexander/src/tuenti/integration && hg pull -u && \
    cd /Users/alexander/src/tuenti/hotfix && hg pull -u && \
    cd /Users/alexander/src/tuenti/stable && hg pull -u && \
    cd /Users/alexander/src/tuenti/release && hg pull -u"

alias rsint="/Users/alexander/bin/rsbranch.py integration"
alias rsrel="/Users/alexander/bin/rsbranch.py release"

# VM server
alias vmstart='VBoxManage startvm tst'
alias vmstop='VBoxManage controlvm "tst" acpipowerbutton'

###################
### Environment ###
###################
# Path to my bin
export PATH=/usr/local/share/python:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH=/Users/alexander/bin:$PATH
export PATH=/usr/local/bin:$PATH

# Python Paths
if [ -d ~/.local/bin ]; then
  export PATH=~/.local/bin:$PATH
fi

if [ -d ~/.local/lib/python2.7/site-packages ]; then
  export PYTHONPATH=~/.local/lib/python2.7/site-packages:$PYTHONPATH
fi
