#!/usr/bin/zsh
###############
### Aliases ###
###############
# Update all standard branches
alias hgupall="\
    cd /Users/alexander/src/tuenti/current && hg pull -u && \
    cd /Users/alexander/src/tuenti/integration && hg pull -u && \
    cd /Users/alexander/src/tuenti/hotfix && hg pull -u && \
    cd /Users/alexander/src/tuenti/stable && hg pull -u && \
    cd /Users/alexander/src/tuenti/release && hg pull -u && \
    cd /Users/alexander/src/tuenti/current"

# VM server
alias vmstart='VBoxManage startvm tst'
alias vmstop='VBoxManage controlvm "tst" acpipowerbutton'

alias fd='fab -f ~/bin/deploy.py'

alias mdb='mongod run --config /usr/local/Cellar/mongodb/2.0.2-x86_64/mongod.conf'

alias cccl="tail -n 20 /Library/Logs/CCC.log"

###################
### Environment ###
###################
# Path to my bin
export PATH=/usr/local/share/python:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH=/Users/alexander/bin:$PATH
export PATH=/usr/local/bin:$PATH

# Python Paths
if [ -d ~/.local/bin ]; then
  export PATH=~/.local/bin:$PATH
fi

if [ -d ~/.local/lib/python2.7/site-packages ]; then
  export PYTHONPATH=~/.local/lib/python2.7/site-packages:$PYTHONPATH
fi

# Alchemy shit
export PATH=/usr/local/src/flex_sdk/bin:$PATH
. /usr/local/src/alchemy/alchemy-setup
export PATH=$PATH:$ALCHEMY_HOME/ackhacks

# Android shit
export ANDROID_NDK=/Users/alexander/android/android-ndk
export ANDROID_SDK=/Users/alexander/android/android-sdk
export PATH=$PATH:$ANDROID_SDK/tools:$ANDROID_SDK/platform-tools:$ANDROID_NDK
