#!/usr/bin/zsh
###############
### Aliases ###
###############
# Build folders #
alias cdstk='cd /var/www/builder.wrk/suntask.qbero.ru/'
alias cdpnt='cd /var/www/builder.wrk/pointer.qbero.ru/'


###################
### Environment ###
###################
export PATH=/home/pepyaka/bin:$PATH
