#!/usr/local/bin/zsh
###############
### Aliases ###
###############
alias ls='ls -F -G'
# Use MacVim as vim
alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'
alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"


##############
### Config ###
##############
# Open strange files with open command on OS X
for s in mp3 wav aac m4a \
    avi mp4 m4v mov qt mpg mpeg mkv \
    jpg png psd bmp gif tif tiff \
    ps pdf html dmg; do
    alias -s $s=open
done


###################
### Environment ###
###################
# Python virtual environment
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
export WORKON_HOME=$HOME/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true
export PIP_REQUIRE_VIRTUALENV=true
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache
# Global installation of pip package
gpip() {
    PIP_REQUIRE_VIRTUALENV="" pip "$@"
}


# Github token for Homebrew
export HOMEBREW_GITHUB_API_TOKEN=2252bd8c5c32c3386fa8df32ddd064c8f6e61c9a

# fzf for Ctrl+r
source ~/.fzf.zsh


##########
## Path ##
##########
# Path to sbin
export PATH=/usr/local/sbin:$PATH
# Path to bin
export PATH=/usr/local/bin:$PATH


#############
## Plugins ##
#############
# Autojump
[[ -s /usr/local/etc/autojump.sh ]] && . /usr/local/etc/autojump.sh
# Syntax highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
