#!/usr/local/bin/zsh
############################
### zsh specific aliases ###
############################
alias :q=exit
function fn() {
    find ./ -name $1
}

# Git aliases
alias gst='git status --short'
alias ga='git add'
alias gaa='git add .'
alias gc='git commit -v'
alias gca='git commit -a -v'
alias go='git checkout'
alias gcb='git checkout -b'
alias gb='git branch'
alias gbs='git show-branch'
alias gba='git branch -a'
alias gd='git diff | mate'
alias gull='git pull'
alias gush='git push'

# Commith with message
function gg() {
    git commit -a -v -m "$*"
}

# Horizontal line in shell
alias hr='printf "%`tput cols`s"|tr " " "#"'

# List
alias lsa='ls -lha'
alias lodd='ls -d -- .*(/)'                 # only show dot-dirs
alias lodf='ls -a -- .*(.)'                 # only show dot-files
alias lod='ls -d -- *(/)'                   # only show dirs
alias loe='ls -ld -- *(/^F)'                # only show empty dirs
alias lsnew='=ls -rtlh -- *(.) | tail $@ 2&>/dev/null'  # only the newest files
alias lsold="=ls -rtl -- *(.) | head $@ 2&>/dev/null"   # display the oldest files
alias lssmall="=ls -Sl -- *(.) | tail $@ 2&>/dev/null"  # display the smallest files
alias lsx='ls -l -- *(*) | head $@ 2&>/dev/null'        # only show executables
alias lsbig="ls -lSh -- *(.) | grep -v total | head $@ 2&>/dev/null"    # display the biggest files

# Stack walking
alias 1='cd -'
alias 2='cd +2'
alias 3='cd +3'
alias 4='cd +4'
alias 5='cd +5'
alias 6='cd +6'
alias 7='cd +7'
alias 8='cd +8'
alias 9='cd +9'

# Ruby console
alias irb='irb --prompt simple --readline -r irb/completion'


################
## Navigation ##
################
alias cdb='cd -'
alias ..='cd ..'
alias ...='cd ../..'
alias ....="cd ../../.."

# Make and go
function take() {
    mkdir $1
    cd $1
}

alias md='mkdir -p'
alias rd=rmdir

# Push and Pop made simple
alias d='dirs -v'
alias pu=pushd
alias po=popd


###############
## Functions ##
###############
extract () {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)      tar xjf $1              ;;
            *.tar.gz)       tar xzf $1              ;;
            *.bz2)          bunzip2 $1              ;;
            *.rar)          rar x $1                ;;
            *.gz)           gunzip $1               ;;
            *.tar)          tar xf $1               ;;
            *.tbz2)         tar xjf $1              ;;
            *.tgz)          tar xzf $1              ;;
            *.zip)          unzip $1                ;;
            *.Z)            uncompress $1           ;;
            *)              echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

# Search through history
h () { history 0 | grep $1 }


#########
## ZLE ##
#########
# Run with sudo by ZLE
run-with-sudo() { LBUFFER="sudo $LBUFFER" }
zle -N run-with-sudo
bindkey '^X^E' run-with-sudo

