#!/usr/local/bin/zsh
############################
### zsh specific aliases ###
############################
alias :q=exit
function fn() {
    find ./ -name $1
}

# Git aliases
alias gst='git status --short'
alias ga='git add'
alias gaa='git add .'
alias gc='git commit -v'
alias gca='git commit -a -v'
alias go='git checkout'
alias gcb='git checkout -b'
alias gb='git branch'
alias gbs='git show-branch'
alias gba='git branch -a'
alias gd='git diff'
alias gdc='git diff --cached'
alias gull='git pull'
alias gush='git push'
alias gt='git tag'

alias gl='git log -C --decorate' 
alias gll='git log -C --decorate -n 5' 
alias glg="git log --graph '--pretty=tformat:%Cblue%h%Creset %Cgreen%ar%Creset %Cblue%d%Creset %s'"
alias gld='git log --pretty=format:"%C(yellow)%h %ad%Cred%d %Creset%s%Cblue [%cn]" --decorate --date=short'
alias gls='git log -C --decorate --stat'
alias glp='git log -C --decorate --stat -p'
alias glf='git log -u'

alias gsr="git lr"
alias gdr="git dr"

alias gfs='git fs'
alias gfsr='git fsr'
alias ggs='git gr'
alias ggsr='git grr'

alias gsl='git sl'
alias gss='git ss'
alias gssp='git ssp'
alias gsp='git sp'
alias gsa='git sa'

alias gr='git r'
alias gr1='git r1'
alias grh='git rh'
alias grh1='git rh1'



# Commith with message
function gg() {
    git commit -a -v -m "$*"
}

alias hgst='hg st'
alias hga='hg add'
alias hgarm='hg addremove'
alias hgc='hg ci'
alias hgu='hg up'
alias hguc='hg up -C'
alias hgl='hg log'
alias hgll='hg log -l5'
alias hglb='hg log -b .'
alias hglbl='hg log -b . -l5'
alias hglr='hg log -r'
alias hggl='hg glog'
alias hgull='hg pull'
alias hgullu='hg pull -u'
alias hgush='hg push'
alias hgo='hg out'
alias hgd='hg diff'
alias hgr='hg revert'
alias hgp='hg purge'
alias hgrp='hg revert --all && hg purge'

# Mercurial commit with message
function hgg() {
    hg ci -m "$*"
}


# Horizontal line in shell
alias hr='printf "%`tput cols`s"|tr " " "#"'

# List
alias lsa='ls -lha'
alias lodd='ls -d -- .*(/)'                 # only show dot-dirs
alias lodf='ls -a -- .*(.)'                 # only show dot-files
alias lod='ls -d -- *(/)'                   # only show dirs
alias loe='ls -ld -- *(/^F)'                # only show empty dirs
alias lsnew='=ls -rtlh -- *(.) | tail $@ 2&>/dev/null'  # only the newest files
alias lsold="=ls -rtl -- *(.) | head $@ 2&>/dev/null"   # display the oldest files
alias lssmall="=ls -Sl -- *(.) | tail $@ 2&>/dev/null"  # display the smallest files
alias lsx='ls -l -- *(*) | head $@ 2&>/dev/null'        # only show executables
alias lsbig="ls -lSh -- *(.) | grep -v total | head $@ 2&>/dev/null"    # display the biggest files

# Stack walking
alias 1='cd -'
alias 2='cd +2'
alias 3='cd +3'
alias 4='cd +4'
alias 5='cd +5'
alias 6='cd +6'
alias 7='cd +7'
alias 8='cd +8'
alias 9='cd +9'

# Ruby console
alias irb='irb --prompt simple --readline -r irb/completion'

# Something like scp, but with rsync
alias mscp='rsync --progress --partial --rsh="ssh" -4'

# Add tab to MacVim with this file
alias avim='mvim --remote-tab-silent'

# Kdiff
alias kdiff='/Applications/kdiff3.app/Contents/MacOS/kdiff3'

alias _='sudo'
################
## Navigation ##
################
alias cdd='cd -'
alias ..='cd ..'
alias ...='cd ../..'
alias ....="cd ../../.."

# Make and go
function take() {
    mkdir $1
    cd $1
}

alias md='mkdir -p'
alias rd=rmdir

# Push and Pop made simple
alias di='dirs -v'
alias pu=pushd
alias po=popd


###############
## Functions ##
###############
extract () {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)      tar xjf $1              ;;
            *.tar.gz)       tar xzf $1              ;;
            *.bz2)          bunzip2 $1              ;;
            *.rar)          rar x $1                ;;
            *.gz)           gunzip $1               ;;
            *.tar)          tar xf $1               ;;
            *.tbz2)         tar xjf $1              ;;
            *.tgz)          tar xzf $1              ;;
            *.zip)          unzip $1                ;;
            *.Z)            uncompress $1           ;;
            *)              echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

alias x=extract

# Search through history
h () { history 0 | grep $1 }

# Functions to search through
phpgrep () {
    curdir=./
    grep -rin --include="*.php" "${1}" ${2:-$curdir}
}

phmlgrep () {
    curdir=./
    grep -rin --include="*.phtml" "${1}" ${2:-$curdir}
}

phagrep () {
    curdir=./
    grep -rin --include="*.phtml" --include="*.php" "${1}" ${2:-$curdir}
}

jsgrep () {
    curdir=./
    grep -rin --include="*.js" "${1}" ${2:-$curdir}
}

allgrep () {
    curdir=./
    grep -rin "${1}" ${2:-$curdir}
}

# Alias for journaling app
alias jn="jrnl -n5"
alias jll="jrnl @log"
alias jle="jrnl --edit @log"
alias jl="jrnl \#log"

#########
## ZLE ##
#########
# Run with sudo by ZLE
run-with-sudo() { LBUFFER="sudo $LBUFFER" }
zle -N run-with-sudo
bindkey '^X^E' run-with-sudo

export GREP_OPTIONS='--color=auto'
export GREP_COLOR='1;32'
